version: '3' # Docker Compose バージョンに対応するファイルバージョンを指定
services:
  app:
    build:
      context: . # ビルド時にカレントディレクトリを起点とする
      dockerfile: ./Dockerfile # context から見た Dockerfile のパスを指定
    ports:
      - '8000:8000' # localhost の 8000 ポートでアクセスできるようにする
    volumes:
      - .:/rails7_api_test
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 8000 -b 0.0.0.0"

  # swagger-uiイメージを同時に立ち上げる
  doc:
    image: swaggerapi/swagger-ui
    volumes:
      - ./doc/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    ports:
      - 8080:8080
