version: '3' # Docker Compose バージョンに対応するファイルバージョンを指定
services:
  app:
    build:
      context: . # ビルドの起点となるパスとしてカレントディレクトリを指定
      dockerfile: Dockerfile.dev # context から見た Dockerfile のパスを指定
      args:
        SOURCE_DIR: /rails7_api_test
    ports:
      - '8000:8000' # localhost の 8000 ポートでアクセスできるようにする
    volumes:
      - .:/rails7_api_test
    tty: true
    stdin_open: true

  # swagger-uiイメージを同時に立ち上げる
  doc:
    image: swaggerapi/swagger-ui
    volumes:
      - ./doc/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    ports:
      - 8080:8080
