openapi: 3.0.2

# API通信テスト時に利用する接続先
servers:
  - url: "http://localhost:8000"
    description: "local api server"

info:
  title: "Rails7 API"
  description: "サンプルアプリ"
  version: "1.0.0"

paths:
  /api/v1/posts:
    post:
      tags:
        - "posts"
      summary: "投稿内容をDBに登録"
      requestBody:
        description: DBに登録する投稿内容
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: "成功時"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

components:
  schemas:
    Post:
      description: "投稿"
      type: "object"
      properties:
        title:
          description: "タイトル"
          type: "string"
          example: test title
        description:
          description: "投稿内容"
          type: "string"
          example: test description
      required:
        - "title"
        - "description"
